#	[ Site Configuration ]
site.app_debug = true
site.version = 1.0
site.name = Jephy MVC
site.email = info@jephy-mvc.loc
site.phone = +23489345678
site.home = http://jephy-mvc.loc
site.app_path = C:/xampp/htdocs/src/jephy-mvc/app
site.home_root_path = C:/xampp/htdocs/src/public
site.encryption_key = gwb8y237872!!@!vegcsi_375126
site.address = 6, Alhaji Azzez Oloruntoyin Street, Ogijo, Shagamu, Ogun State, Nigeria
site.title 	= Jephy MVC - The light weight and portable PHP MVC framework that runs anywhere
site.keywords = jephy, mvc, php
site.description = Jephy MVC is a light weight and portable PHP MVC framework that runs locally,  on shared-hosts, vpc, dedicated server and cloud in general.

site.url.home = http://jephy-mvc.loc
site.url.third_party_platform.github = https://github.com/jephymvc/jephy-mvc-01

site.author.fullname = Afolabi Oloruntola
site.author.email = afolabi.oloruntola@gmail.com

#	[ Database Configuration ]
# 	Driver can be either mysql, pgsql, sqlsrv and sqlite
database.driver = mysql
database.host = localhost
database.name = jephymvc_db
database.user = root
database.password = 

#	[ Mail Configuration ]
mail.host = localhost
mail.smtp_auth = false
mail.username = support@jephy-mvc.loc
mail.password = r5gfew44@34322wew

#	Enable SMTP debugging
#	0 = off (for production use)
#	1 = client messages
#	2 = client and server messages
mail.smtp_debug 	= 1
# 	Could be one of tls, ssl and none
mail.encryption = none
mail.port.tls = 25
mail.port.ssl = 25
mail.address.from = support@jephy-mvc.loc
mail.address.name = Jephy MVC
mail.address.password = refewgewvwe3244121@#!
mail.is_html = true
mail.charset = UTF-8

#	[ Session ]
session.admin 	= admin
session.guest 	= guest
session.keys 	= guest|admin

#	[ Graphql ]
debug 				= true
enable_playground 	= true
graphql.endpoint 	= graphql
graphql.playground_theme = dark


